name: tests
on:
  pull_request:
    paths:
      - 'tickets/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup and run tests
        run: |
          ls ${{ github.workspace }}
          node -v
          cd tickets
          npm install
          npm run test:ci
